### PR TITLE
+ example linking febrl4 (a and b) datasets

### PR DESCRIPTION
**Pull request by ADBond**
An example notebook linking the febrl4 dataset tables, including a sketch of a typical workflow, using several splink features, a slight comparison of different models, and a reasonable amount of commentary.

### CODE REVIEW

**Comment by ADBond** [comment]
Please do let me know if I've made any errors, or have misunderstood anything/said anything misleading. I tried to avoid making it _excessively_ detailed/large, but I realise there is a reasonable amount in this, so happy to trim down if it's too dense - just thought it might be useful to display a few different features/concepts in additional ways to how they are presented elsewhere.

**Comment by RobinL** [comment]
This is brilliant.  I noticed a very small typo:
`the aim here is that we generate very true false positives`

**Review by RobinL — APPROVED** [review]

**Comment by ThomasHepworth** [comment]
Can we add a new section to [00_Tutorial_Introduction](https://github.com/moj-analytical-services/splink_demos/blob/examples/febrl4ab-link/00_Tutorial_Introduction.ipynb) to cover all of these new demos?

**End-to-end Demos**
☝️or something along those lines.

**Comment by ThomasHepworth** [comment]
I can't actually add comments on directly into the `.ipynb` file as it's too large... so hopefully these random comments make sense.

Screenshot 2022-10-07 at 10 53 09
☝️
```
For variables that aren't used in the m-training blocking rules, we have two estimates --- one from each of the training sessions (see `street_number`, for example)
```

**Comment by ThomasHepworth** [comment]
Screenshot 2022-10-07 at 10 55 06

Chart is broken.

I've noticed something similar happening with another graph and I'm trying to diagnose the issue... not entirely sure what's wrong with it though :(

**Comment by ThomasHepworth** [comment]
Screenshot 2022-10-07 at 10 58 07

Maybe link through to Robin's articles in case someone is interested in what you mean by `... prevalence of coincidences and mistakes`. [Articles](https://www.robinlinacre.com/maths_of_fellegi_sunter/)

**Comment by ThomasHepworth** [comment]
Spelling error here:
`Similarly, we can look at the non-links which are performing the best, to see whether we have an issue with falst positives.`

**Pull request merged**
