### PR TITLE
Fixing typos and very minor cleanup

### PR DESCRIPTION
**Pull request by ADBond**
Just fixing a few typos and similar.

### CODE REVIEW

**Comment by ThomasHepworth** [comment]
@ADBond I am guessing you did this on the AP? We have automatic stripping of jupyterlab outputs on there, which means that none of the cells have been run and all outputs are missing (hence the -8k lines you have).

Can you run this the jlab notebooks locally on VSCode? Alternatively, Robin or I can do

**Comment by ADBond** [comment]
> @ADBond I am guessing you did this on the AP? We have automatic stripping of jupyterlab outputs on there, which means that none of the cells have been run and all outputs are missing (hence the -8k lines you have).
> 
> Can you run this the jlab notebooks locally on VSCode? Alternatively, Robin or I can do

@ThomasHepworth Yep, just noticed that. Had thought I had resolved that by adjusting the hook for this repo, but obviously got a little tangled along the way. Think I should be able to fix it, but will let you know if I have any difficulty

**Comment by RobinL** [comment]
Ah yes!  So to clarify, in almost all cases working at MoJ, what you've done is what we'd want -  i.e. to strip out the outputs.  This is because we don't store sensitive data in Github, and Jupyter outputs can contain e.g. personal identifiers

But this repo is an exception, because
- none of the data is sensitive
- the outputs make their way into the main docs herehttps://moj-analytical-services.github.io/splink/demos/01_Exploratory_analysis.html

so we want to keep them!

**Comment by ADBond** [comment]
> Think I should be able to fix it, but will let you know if I have any difficulty

@ThomasHepworth I'm afraid I misjudged the nature of the issue - hadn't realised output was stripped via git config as well. Can't run VSCode locally on my machine currently, so may need a hand restoring the output (although non-urgent)

**Comment by ADBond** [comment]
There is also [this section](https://github.com/moj-analytical-services/splink_demos/blob/master/03_Estimating_model_parameters.ipynb?short_path=7006708#L206-L219) where the text just abruptly cuts off - wasn't really sure exactly where this was going so didn't really feel qualified to fix

**Pull request merged**
